### PR TITLE
Added ability to disable vibration for TimePicker.

### PR DESCRIPTION
**Pull request by raymondlam**
Also, added a fix to preserve the vibration settings for the DatePicker when the dialog is recreated (eg. device rotation).

### CODE REVIEW

**Comment by flavienlaurent** [comment]
great, thanks!

**Comment by flavienlaurent** [comment]
great thanks!

**Comment by flavienlaurent** [comment]
@edisonw is right. See http://android-developers.blogspot.fr/2012/05/using-dialogfragments.html

I re add empty constructors 2bb5113a8d09cff29253141f520c02d0c8530f40

**Comment by edisonw** [comment]
@flavienlaurent thanks for finding the reference, I just remember they are used from long time ago, was not able to find the reference to support my claim earlier. :)

**Comment by raymondlam** [comment]
@flavienlaurent I've never had problems with having no constructors. The android docs do not include the constructor, http://developer.android.com/reference/android/app/DialogFragment.html.

I thought that the empty constructor used in the example was just a reminder to people incase they overload the constructor. By default, if there are no constructors, the default constructor should provide the same effect as an empty constructor. If there is an overloaded constructor, no default constructor will be created so they need to explicitly include a no-parameter constructor so that it can be re-created by the system.

I was just curious if there were any specific cases where having no constructors would cause an error.

But that point aside, we can leave the constructors as in as there is no harm.

**Comment by edisonw** [comment]
@raymondlam to be honest I am not sure where they are used as well, it's there in the source code though: https://android.googlesource.com/platform/frameworks/opt/datetimepicker/+/master/src/com/android/datetimepicker/date/DatePickerDialog.java

**Pull request merged**
