### PR TITLE
Add method to highlight days

### PR DESCRIPTION
**Pull request by cbruegg**
This PR fixes the build in newer versions of Android Studio and adds a method `DatePickerDialog.setHighlightedDays(List<CalendarDay>)`. The supplied days are highlighted in orange.
A use case: Highlighting days that have appointments to allow a user to quickly switch to them.

### CODE REVIEW

**Comment by cbruegg** [comment]
Flavien, there are many open PRs for this project that don't have any response. Are you still maintaining this project? If not, it would be great if you could add a warning that this project isn't maintained anymore. I'd be willing to take over maintainance, so feel free to link to my repo if you're adding a warning.

**Comment by SimplicityApks** [comment]
It's really a problem that this isn't maintained any more. I've used [jaydeep17's fork](https://github.com/jaydeep17/datetimepicker) so far, but he hasn't been active for a couple of months as well. You'd need to activate issues for me to switch to your fork with [ReminderDatePicker](https://github.com/SimplicityApks/ReminderDatePicker) and I'd need jaydeep's changes as well. Also a release to jcenter would be convenient. However, I just found [another fork](https://github.com/lachlanm/datetimepicker) that looks promising, but haven't got a chance to test it.

**Comment by cbruegg** [comment]
It looks like these forks differ quite a lot from the original one here, so it would probably be the best option to switch to one of them. I'd bet that my PR here wouldn't even be mergeable into jaydeep17's or lachnam's forks.

I'll open issues on my fork anyway, but I won't actively try to integrate jaydeep17's changes. If you'd like to do that, please open a PR and I'll have a look.

**Comment by SimplicityApks** [comment]
I'll see what I can do when I get the time... Yeah there are really a ton of changes but important ones as well to keep up with Material design for instance

**Pull request closed without merging**
