### PR TITLE
June comes out as month number 5 in the sample.

### PR DESCRIPTION
**Pull request by nikhilesh-payyavuala**
Added 1 to the month variable

### CODE REVIEW

**Comment by flavienlaurent** [comment]
seriously ?

http://docs.oracle.com/javase/7/docs/api/java/util/Calendar.html#MONTH

**Comment by nikhilesh-payyavuala** [comment]
In the sample application when you are toasting the value of the month it shows june as 5.

**Comment by flavienlaurent** [comment]
Just read this http://docs.oracle.com/javase/7/docs/api/java/util/Calendar.html#MONTH

**Comment by nikhilesh-payyavuala** [comment]
Ok it is nothing but you don't show june as 5 in the application when you are printing it out as year - month - day right? Sorry about that anyway.

**Pull request closed without merging**
